const SCREEN_NAMES = {
  LOGIN: 'LOGIN',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD',
  HOME: 'HOME',
  ABOUT: 'ABOUT',
  CONTACT: 'CONTACT',
  PROFILE: 'PROFILE',
  ORDERS: 'ORDERS',
};
export default SCREEN_NAMES;
